services:
  - name: web
    env: python
    buildCommand:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi --bind 0.0.0.0:8080
